import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className + ' relative min-h-screen flex items-center justify-center'}>
        {/* Diamond frame */}
        <div className="relative w-[50vmin] aspect-square rotate-45 border-8 border-white">

        {/* separator lines */}
        <div className="absolute inset-0 pointer-events-none">
              <span className="absolute left-1/2 top-1/2 w-[200%] h-[2px] bg-white -translate-x-1/2 -translate-y-1/2 rotate-[25deg]" />
              <span className="absolute left-1/2 top-1/2 w-[200%] h-[2px] bg-white -translate-x-1/2 -translate-y-1/2 rotate-[-35deg]" />
            </div>

          <div
        className="absolute inset-0 -z-10"
        style={{
          /* first cut at 10°, second cut at 70°  →  black | red  */
          background:
            'conic-gradient(from -65deg at 50% 50%,' +
            ' #000 0 120deg,' +      // black up to the 2nd cut
            ' #dc2626 120deg 180deg,' + // red afterwards   (Tailwind red-600)
            ' #000 180deg 300deg, ' +
            ' #dc2626 300deg 360deg)'
        }}
      />
          <div className="-rotate-45 flex items-center justify-center w-full h-full">
            

            
            {children}
          </div>
        </div>
        

        {/* theme switch  light bulb */}
      </body>
    </html>
  );
}
